# yml을 자주 쓰는 확장자
# key / value 형식으로 이루어져있음
# tabdmfh rnqnsgka
# 워크플로우 -> 자동화 할 작업의 설계서  --> action.yml 그 자체
# jobs :  작업 단위 ( 테스트 시켜줘, 빌드시켜줘, 이슈 닫아줘 )
# 워크플로우 > job이란작업단위가 있음
# 실행환경 : git 회사의 가상 환경 , 내 코드를 git은 모름
# step: job > step 이 포함되어있음
# job(작업단위)가 실행되기 위해서 완수해야할 단계(step)
# 1. 코드를 colone
# 2. npm i
# 3. npm start?

name: first workflow
on: push
jobs:
  # job의 이름
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo 'hello wold'
