name: Environment Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Default
        run: |
          echo  "레퍼지토리 : $GITHUB_REPOSITORY"
          echo "퍼지토리 : $GITHUB_SHA"
          echo "레퍼지토리 : $GITHUB_REF"
