name: event action
on:
  push:
    #  src 경로에 있을때만 이벤트 발생하도록
    paths: "src/**"
  pull_request:
    branches: "main"
    types: [closed]
jobs:
  #job 실행
  lint:
    runs-on: ubuntu-latest
    steps:
      # 코드를 가져오는 git action을 import 해야하지
      - name: checkout
        uses: actions/checkout@v4

      - name: npm NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 이제 페키지 js 가져오기
      - name: npm Ci
        run: npm ci

      # 이제 lint 하기
      - name: lint
        run: npm run lint
